src/asset-catalog/asset-search-view.js

pagination fix

---

.gitignore
LICENSE
README.md
package-lock.json
package.json
polymer.json
src/my-app.js
test/index.html
wct.conf.json

Remove random "OK" button from the login page

---

src/my-app.js

Query proper element for paper-dialog #9

---

.azure-pipelines/merge.yml
.azure-pipelines/verify.yml

- renames folder for azure yaml files to .azure-pipelines
- moves existing merge build & renames
- adds PR build

#2 rename pipelines & add verify

---

README.md

Test of PR trigger
Also adds simple link to builds

#2 Add quick info about builds -- to test PR trigger and check

---

src/asset-lineage/asset-lineage-view.js
src/common/happi-graph.js

Fix clearGraph method on new empty data

---

src/asset-catalog/asset-catalog-view.js
src/asset-lineage/asset-lineage-view.js
src/glossary/glossary-view.js
src/my-app.js
src/repository-explorer/diagram-manager.js
src/repository-explorer/filter-manager.js
src/repository-explorer/instance-retriever.js
src/type-explorer/neighbourhood-diagram.js

Add defaults to switch cases and reindent files

---

src/common/role-components.js
src/forbidden403Page.js
src/home-page.js
src/my-app.js

Fix deep linking page permissions

---

src/my-app.js

Fix permissions on page when components array is empty list

---

src/login-view.js

Signed-off-by: Alexandra Bucur <alexandra-nona.bucur@ing.com>

Change feedback for different authentication errors

---

src/asset-lineage/asset-lineage-view.js

fixed value sent to asset tools

---

src/asset-catalog/asset-search-view.js

fix multi-select combo (searched types) not responding after a search

---

src/my-app.js

Crumbs fix and Asset Lineage removal from left menu

---

src/asset-lineage/asset-lineage-view.js

added displayName in the node table properties, changed the reload bu…tton functionality to only re-execute the  call  and not reload the page

Change graph reload button

---

src/asset-lineage/asset-lineage-view.js
src/common/item.js
src/my-app.js

Fix current clicked element in asset lineage page

---

package-lock.json
package.json
src/asset-catalog/asset-search-view.js
src/login-view.js

added load more oprion

---

src/asset-catalog/asset-tools.js

url value fix

---

src/asset-lineage/asset-lineage-view.js
src/common/happi-graph.js

I have also added an example of how it looks

added node context in the details pop-up

---

about.js
src/asset-lineage/asset-lineage-view.js
src/common/props-table.js

Fix table width on modal and remove reload button

---

src/asset-lineage/asset-lineage-view.js
src/my-app.js

Fix component load at page switch for asset-lineage

---

src/user-options-menu.js

add logout server side

---

src/my-app.js

removed redirect to /#/home-page

---

src/my-app.js
src/user-options-menu.js

fix redirects

---

src/common/happi-graph.js

Add tooltip on header and property

---

src/asset-lineage/asset-lineage-view.js
src/common/graph-algorithms.js
src/common/happi-graph.js

- add support for horizontal graph display
- fix ETL Jobs toggle button

Add support for horizontal graph display

---

package-lock.json
package.json
src/common/graph-algorithms.js

- remove code duplication
- bump version to 1.1.1

Remove code duplication and bump version

---

src/asset-lineage/asset-lineage-view.js
src/common/happi-graph.js

Fix has size in Asset Lineage

---

src/asset-catalog/asset-search-view.js
src/asset-lineage/asset-lineage-view.js
src/toast-feedback.js
src/token-ajax.js

Add timeout for ajax requests

---

src/common/happi-graph-legend.js

Change toggle legend button

---

src/common/graph-group-icon-map.js

Signed-off-by: Raluca Popa <raluca.popa2@ing.com>

Add CSVFile to icon map

---

src/asset-lineage/asset-lineage-view.js
src/common/happi-graph-legend.js
src/common/item-group-icon-map.js

refactor item icons

---

src/asset-catalog/asset-search-view.js
src/common/item-group-icon-map.js

add mission icon mapping

---

src/asset-lineage/asset-lineage-view.js
src/common/happi-graph-statistics.js
src/common/happi-graph.js

Add statistics feature in happi-graph

---

src/common/happi-graph-statistics.js

Update column name

---

.gitignore
index.html
package.json
polymer.json
prebuild.js
src/login-view.js
src/my-app.js
src/token-ajax.js
themes/css/style.css

It will ignore everything and build statically with no API_URL prefix:
```bash
$ npm run build 
```
Will prefix this value to any "/api/resources" endpoint resulting in http://my-api.app/api/resources requests:
```bash
$ npm run build --api-url=http(s)://my-api.app
```
Which will actually run `npm run start --api-url=http://localhost:9000`, the API_URL in this scenario is the `egeria-api-mocks` project started locally on http://localhost:9000:
```bash
$ npm run start:dev
```
It also breakchanges the way the theme is loaded, i move the default css to `themes/css/style.css`, which means that if we want to load other theme we need to overwrite that file.

Implement API_URL config parameter in ENV params

---

package-lock.json
package.json

Bump versions as dependantbot mentioned

---

package-lock.json
package.json

Bump version to 1.2.0

---

src/asset-catalog/asset-qualified-name-view.js

fix qualified-name-view for in case of no match

---

Dockerfile

#108 Switch to node 10 in Docker build

---

.github/workflows/node-build.yml
package-lock.json

* Revert accidental update of package-lock.json
* Adds reporting of node/npm version in build
Thanks for pointing out @sarbull -- since the file isn't in .gitignore it's somewhat easy to accidentally include.

#108 revert incorrect update to package-lock.json

---

.github/workflows/node-build.yml

Pin node to 10.13.0

---

about.js
package.json

Generate about.json file with commitId and datetime of build

---

src/about-view.js

Update about page

---

src/common/role-components.js
src/my-app.js
src/user-options-menu.js

fix component visibility according to roles

---

new/egeria-app.container.js

Add fix for user roles

---

package-lock.json
package.json

Bump happi-graph version to fixed 2.8.1

---

new/asset-lineage/egeria-asset-lineage.container.js
new/commons/fetch.js
new/egeria-app.container.js
new/egeria-home.component.js
themes/css/style.css

Get asset details for breadcrumb details and vertical tab check

---

new/asset-catalog/egeria-asset-details.component.js

Add classifications component data

---

new/asset-catalog/egeria-asset-details.component.js

Add collapsible for classification

---

new/asset-catalog/egeria-asset-details.component.js

Set min-height:100% in asset details component

---

new/asset-catalog/egeria-asset-details.component.js
new/commons/egeria-item-utils.behaviour.js

Add properties key on classification tables

---

package-lock.json
package.json

Update happi-graph version to main branch

---

new/asset-catalog/egeria-asset-search.component.js

Fix decoded q param

---

new/asset-catalog/egeria-asset-tools.component.js
new/egeria-single-page.component.js
new/repository-explorer/egeria-repository-explorer.component.js

Fix repository-explorer url params

---

package-lock.json
package.json

bump version of egeria-js-commons

---

new/asset-catalog/egeria-asset-search.component.js
new/egeria-single-page.component.js

adjust height for content

---

new/repository-explorer/connection-manager.js

TEX and REX fix

---

new/asset-catalog/egeria-asset-tools.component.js

remove unused property and api request

---

new/commons/fetch.js
new/egeria-app.container.js

Remove forbidden page before logging in

---

package-lock.json
package.json

- fixed wrong urls used for happi-graph and egeria-js-commons in npm dependency list

Fix package.json and package-lock.json

---

new/egeria-app.container.js
polymer.json

Quickfix forbidden page checks and use .min.js on ELK to improve build time

---

new/asset-lineage/egeria-asset-lineage.container.js

Fix reload lineage button

---

new/asset-lineage/egeria-asset-lineage.container.js

fixed the same issue for toggle etl job button

Fix lineage reload button

---

README.md
new/asset-lineage/egeria-asset-lineage-viewer.component.js
package-lock.json
package.json

Change happi-graph algorithm to ELK

---

new/asset-lineage/egeria-asset-lineage-viewer.component.js
polymer.json

Add .min.js

---

package-lock.json
package.json

Bump egeria-js-commons to v0.2.1

---

package-lock.json
package.json

Update happi-graph and egeria-js-commons versions

---

package-lock.json
package.json

Bump version to 2.11.0

---

package-lock.json
package.json

Update happi-graph version to main

---

new/asset-catalog/egeria-asset-tools.component.js

updated to display lineage button for tabularFileColumn

---

new/asset-lineage/egeria-asset-lineage-viewer.component.js

Add nodeCountLimit config in happi-graph

---

package.json
preinstall.js

Add preinstall script

---

package-lock.json
package.json

Bump happi-graph and egeria-js-commons versions

Preparation for 3.0.0

---

package-lock.json
package.json

Change happi-graph version to main

---

new/asset-catalog/egeria-asset-search.component.js

Handle search history

---

new/asset-catalog/egeria-asset-details.component.js
new/asset-catalog/egeria-asset-search.component.js

added search results origin information

---

package-lock.json

Update happi-graph dependency

---

new/asset-catalog/egeria-asset-catalog.container.md
new/asset-catalog/egeria-asset-details.component.md
new/asset-catalog/egeria-asset-search.component.md
new/asset-lineage/egeria-asset-lineage.container.md
new/breadcrumb/egeria-breadcrumb.component.md
new/egeria-about.component.md
new/egeria-app.container.md
new/egeria-error-page.component.md
new/egeria-home.component.md
new/egeria-login.component.md
new/egeria-single-page.component.md
new/egeria-spinner.component.md
new/egeria-user-options.component.md
new/glossary/egeria-glossary.component.md
new/type-explorer/connection-manager.md
new/type-explorer/egeria-type-explorer.component.md

Add md files for components documentation

---

new/commons/fetch.js

Add handler for 401 status code

---

new/egeria-app.container.js
package-lock.json

Unauthenticated deep link should redirect to login with redirect query parameter to get back after successful authentication.

Fix deeplink redirect to login

---

new/commons/fetch.js
old/token-ajax.js
prebuild.js

Implement request timeout feature

---

.github/workflows/node-build.yml

Add platforms for multi-architecture images
This is related to https://github.com/odpi/egeria/issues/2391
Signed-off-by: Theo Thomas <tcn.thomas@googlemail.com>

Add ARM64 platform to Docker Build

---

new/egeria-app.container.js
new/egeria-home.component.js
package.json

extract currentUser from jwt

---

package-lock.json
package.json

Releasing v3.2.0
Changes:
- Using updated JWT auth. token.
- Reworked and improved redirects handling
- Publishing docker image to additional registry
- url parameter handling improvement (etl processes flag)
- remove unused functionality (soruce and destination toggle) + code cleanup

Release 3.2.0

---

react-ui/package-lock.json
react-ui/package.json
react-ui/public/index.html
react-ui/src/index.tsx

Prepend public path for react-ui deployed ui

---

new/egeria-app.container.js

avoid flipping page before redirect to login

---

react-ui/src/App.scss
react-ui/src/components/Login/index.tsx
react-ui/src/services/authentication.service.ts

Display message on incorrect username or password

---

react-ui/src/components/AssetCatalog/helpers.tsx
react-ui/src/components/AssetCatalog/index.tsx
react-ui/src/components/Home/index.tsx

Fix asset-catalog url from home page

---

react-ui/package-lock.json
react-ui/package.json
react-ui/src/components/AssetCatalog/helpers.tsx
react-ui/src/components/AssetCatalog/index.tsx
react-ui/src/components/AssetCatalog/qualified-name.scss
react-ui/src/components/AssetCatalog/qualified-name.tsx

Implement missing qualified name feature

---

react-ui/.env
react-ui/package.json
react-ui/public/index.html
react-ui/src/App.tsx
react-ui/src/components/Assets/Catalog/index.tsx
react-ui/src/components/Assets/Details/index.tsx
react-ui/src/components/Home/index.tsx
react-ui/src/components/Login/index.tsx
react-ui/src/index.tsx
react-ui/src/services/authentication.service.ts

Refactor ENV param for /react-ui

---

new/asset-lineage/egeria-asset-lineage.container.js

add tabel header filters

---

new/egeria-single-page.component.js

added popup for full screen

---

new/asset-lineage/egeria-asset-lineage-viewer.component.js
new/asset-lineage/egeria-asset-lineage.container.js
themes/css/style.css

Added link (edge) selection

---

package-lock.json
package.json

Updated happi graph version

---

new/asset-catalog/egeria-asset-tools.component.js
new/asset-lineage/egeria-asset-lineage.container.js
package-lock.json
package.json

Display the lineage tabs based on the config defined in egeria-js-commons
Note: egeria-js-commons version needs to be updated before merge

Lineage Navigation improvements

---

package-lock.json
package.json

Updated happi-graph version

---

react-ui/package-lock.json
react-ui/package.json
react-ui/src/App.tsx
react-ui/src/components/About/lit.js
react-ui/src/components/Assets/Catalog/index.tsx
react-ui/src/components/Assets/Details/index.tsx
react-ui/src/components/Home/index.tsx
react-ui/src/components/Lineage/Viewer/index.tsx
react-ui/src/components/Lineage/Viewer/name-suggestions.tsx
react-ui/src/components/Lineage/Viewer/types-suggestions.tsx
react-ui/src/helpers/auth-header.test.ts
react-ui/src/helpers/auth-header.ts
react-ui/src/helpers/egeria-fetch.ts
react-ui/src/services/lineage.service.ts

Added lineage viewer component

---

package-lock.json
package.json
src/components/AppInstance/index.tsx
src/index.tsx

Implement <AppInstance />

---

package-lock.json
package.json
src/components/AppInstance/index.tsx

Implement main menu from props

---

.github/workflows/node-build.yml

Update .github settings

---

Dockerfile

Fix new build path

---

src/components/AppInstance/index.tsx

Encapsulate login required components

---

package-lock.json
package.json

Bump version to 3.2.2

---

package-lock.json
src/index.tsx

Add print functionality

---

package-lock.json
package.json
src/components/AppInstance/index.tsx
src/index.tsx

Signed-off-by: Iliescu Cristian-Mihai <cristianmihaiiliescu@gmail.com>

Fix PDF export for lineage

---

package-lock.json
package.json

Signed-off-by: Iliescu Cristian-Mihai <cristianmihaiiliescu@gmail.com>

updated egeria-ui-components version

---

package-lock.json
package.json
src/components/AppInstance/index.tsx
src/index.tsx

Signed-off-by: Iliescu Cristian-Mihai <cristianmihaiiliescu@gmail.com>

Added permissions on routes

---

Dockerfile
about.js
package-lock.json
package.json

should fix https://github.com/odpi/egeria-ui/issues/573

Docker fix

---

.github/dependabot.yml

Remove myself from dependabot assignments

Remove @planetf1 from codeowners/dependabot assignment
